apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: traefik
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true