apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: traefik
      helm:
        valueFiles:
          - values.yaml

    - repoURL: 'oci://quay.io/jetstack/charts/cert-manager'
      targetRevision: 'v1.19.2'
      chart: cert-manager
      helm:
        releaseName: cert-manager
        values: |
          crds:
            enabled: true

    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: ingress
      
    # - repoURL: https://github.com/ZakDaMack/homelab
    #   targetRevision: HEAD
    #   path: crowdsec
    #   helm:
    #     valueFiles:
    #       - values.yaml


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true