apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: portfolio
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: ghcr.io/traefik/helm/traefik
      targetRevision: 37.2.0
      chart: traefik
      helm:
        releaseName: traefik
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/ZakDaMack/homelab'
      targetRevision: HEAD
      path: traefik
      ref: values
    - repoURL: https://github.com/ZakDaMack/homelab
      targetRevision: HEAD
      path: ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true