{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "config-secret",
    "namespace": "default",
    "annotations": {
      "sealedsecrets.bitnami.com/namespace-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "config-secret",
        "namespace": "default",
        "annotations": {
          "sealedsecrets.bitnami.com/namespace-wide": "true"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "unifi_password": "AgAfjCy7zECzfspXghRI4VsDBZjgchpApdhSdHrrDno24liBqVK/flMN30kUWekpdNJa6UnZ8OSHifpWerUBVPE2fctFRtZKLU11mP5oomhgHYDCM9V32u/5Rp8KP79Y/vGlzt2yCniSjS/7+xk5MA9qRHa398k2w+72GxHU4gkBA3+hQAsFvXZN3AoAKkHWHrBlFJuef1sz0dVxwVdMSFsD9okJ6On50xPj0Qk/Qq7OSD3MVt7mBcvIHSxhxXnlUYTolewSF2s7OrNSYSbUCO//k33Z+tZaN1ab1XQmAsdswuJIEE1kKjDUPEGrG49rDbjvvBD1/CEHUciPFkx/HYGNKwmFRsm7G53RRl28sVOmVhpRq9CPCbGeh63HUHZOGYhWq/lkkhB/gzRsP8fulNNBC5T7OfGmyZ8/bqvzjYEk1gAXdyvNnRkd2HpnG8ZEPcAnt1+gbtOJSKwJF5YiBaSVnzqSgrdKB9t/Ocs1IchkxuyujlXy9nQ0N873K4V7pxaKGIKVdDLwWOn+EvB2mn6Ucd+cKdRp4Ul0zcWRGDZQ62HDyrj+fJ8VqhgKBDVOGjVppJI/PakyL9u5i/07e4ZON31uxmWCV/b2SzxOg41OD0lnLsNxLFl2ICuTqKZlWsOkebljKyo4ueCWnOvto8Le5hzci3sb1oR97IaDxwZY229+xP9qnqtgOuqQSoKxLX/QU3osr8VD/cstJUgNEw==",
      "unifi_username": "AgAbXCbWpaw/T4WZWltv5060s0hsrr+Ig8DUA/E+CXdX37oAyrpRvXED5a23ajdSnIB3AafGT9MoeZsx+GysOWrWP52cFAfnoQheV4/AeSpBmjiATDWl4A26ELsJyLlovpcyU9Nd0+JRbj9bfqHEwmC0t/T6MAU/ZEnTymKc/FoVjRMWFNZw0J/BQakpBLN6e0a+NmSDXKdirc9QBwGIGG93Y+NBa62+UNrkHlWef4cGKC2k/9Xd+r8ylF/FPwWT2f+0P4zH6wL4wQYYkVnlRAeTM0kb3lXCJuwNz04X/iGoA/ZMSd5uEUwgExc93k0S/rQcMULQvgXp6T5HQp9Y4mQr8ClgRtBCWs9QutvtUHtlYJqpzgrLqltSH8M1rj76v3ziNbA3Kix1TcqVw6uXLdx4+XjBX8w/hnkdC//2ZW4HZVBv17hBBMoDV06JZ+NqFv9AYeUQXzf+qT/GQ/BArur6g+xhnesdwJoNrekjNyov9IvlPVwknqZ2r/3cOdSkggKAsOSBCW7NbHXTBpHK8w33pa2/vVIYdhyvtXZTmWtpOI8eWzUIarN3gXleWh8Z4Tvt6Lq6wkHAxoUC55gw1uIKhvjWYgmEvnox2MY+Oz4dDXMS+zP1Q/yww0UrPzMxI5fRalT+yHDjcGZ/z9WI5YUctQWRMZiFynABx93EFMe2ZWab5mMWLzjKEBne4oxIFACyqQM=",
      "weather_apikey": "AgA+2prSsUMm7xCKM9TVG8Pa8AMAzC2akurtFLu1cIXU2L2pG4YSXR5FiGb6DxrwToED2mVpW4lNeUQetCEW06MB7NvYtkQYgSFb2moPfJAn+QHKG8DKebVhoYnhN7Lq4DJsSjg7QFhPycE8Vga87q8HaWS07sg3+n4rZrqNt8X4/NVdMUd0eSdoCXPvELzKi+49hNSXJjcaTmM2jGdwvf6KtEFfFaqHYq0DMUzHR28nsLLjK3t7V1sqOnGaRr0FOtXxPkb31sJfrMHpn7gUqh0JNAoeZVDdBRa7ottlpKqXPtw2WgJ2XHTnYKTp75/pKQJxksJ/PHU1zd6hn3x/CahfIz98XCGhjgYlH6NvlL0s0ni8hzl+ag25Mb9AZ8qar5cEQ9SFAQNjCAXYquhkOFBsgElYhnvzvEOV7x48eoO9CGoOzQo34NwU/Cfcr3z6HmTQLR3/V0YN6zpfgmfsPbdElpamU41A7d3f40RIRGyV7zpig5rFY0eI5gx7ybntCLnPw50e6Hcb++3zH0UvemY8T7c5ejPAjNM9JyDI+LqrZod6G2m4URrBFPjI4oJjPm/IKDZk9pcM5aGeHvO83EFkyaWI1+Q3Dv3MvhW/sTnnOPzHxE+qEOYZqATamOLmD2DcnBCa/tsnfkjh0/bH2xhjurYi3bD8NqmTH6BUON9VQFVGLrlAvVMxcsuXYZLMLwYiRSQ332YK0RaEPBMfwthtTQX6W1kjHeN0ZtTHC1My3w=="
    }
  }
}
